version: "3.8"

services:
  register:
    image: ghcr.io/sarcophagus-org/sarcophagus-v2-archaeologist-service:alpha
    network_mode: "host"
    profiles: ["register"]
    env_file:
      - ./.env
    command:
      - /bin/bash
      - -c
      - |
        npm run peer-id-gen
        NODE_NO_WARNINGS=1 npm run cli register -- -g --network ${NETWORK}
    volumes:
      - type: bind
        source: ./peer-id.json
        target: /home/node/app/peer-id.json
    stdin_open: true
    tty: true
    environment:
      FORCE_COLOR: 1
      NODE_NO_WARNINGS: 1

  archaeologist:
    image: ghcr.io/sarcophagus-org/sarcophagus-v2-archaeologist-service:alpha
    networks:
      service_network:
    profiles: ["service"]
    restart: on-failure
    env_file:
      - ./.env
    command:
      - /bin/bash
      - -c
      - NODE_NO_WARNINGS=1 npm run cli start -- --network ${NETWORK}
    volumes:
      - type: bind
        source: ./peer-id.json
        target: /home/node/app/peer-id.json
    stdin_open: true
    tty: true
    environment:
      FORCE_COLOR: 1
      NODE_NO_WARNINGS: 1
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: ${DOMAIN}
      NETWORK: "all"
    expose:
      - "9000"
    depends_on:
      - nginx-proxy
      - acme-companion

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    profiles: ["service"]
    restart: on-failure
    networks: 
      service_network:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs

  acme-companion:
    image: nginxproxy/acme-companion
    restart: on-failure
    networks:
      service_network:
    profiles: ["service"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html 
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    depends_on:
      - nginx-proxy
  
  seed-gen:
    image: ghcr.io/sarcophagus-org/sarcophagus-v2-archaeologist-service:alpha
    profiles: ["seed-gen"]
    command:
      - /bin/bash
      - -c
      - npm run seed-gen
    stdin_open: true
    tty: true
    environment:
      NODE_NO_WARNINGS: 1

networks:
    service_network:

volumes:
    certs:
    vhost:
    html:
    acme:
